[package]
name = "sudoku"
version = "0.1.0"
edition = "2024"

[features]
generate-pdf = ["dep:typst", "dep:typst-pdf", "dep:serde_json", "dep:time"]

[dependencies]
rand = "0.10.1"
serde = { version = "1.0.228", features = ["derive"] }
typst = { version = "0.15.1", optional = true }
typst-pdf = { version = "0.15.1", optional = true }
serde_json = { version = "1.0.150", optional = true }
time = { version = "0.3.55", features = ["local-offset"], optional = true }
